### ISSUE TITLE
ESPHome Setup: Can’t connect to ESP. Please make sure your YAML file contains an ‘api:’ line.

### ISSUE THREAD

**Issue by chondro878** [EverythingSmartHome/everything-presence-lite#145]
I am following the documentation for the Everything Presence Lite - This is my first ESP device, and I when trying to connect it to HA I am getting: “Can’t connect to ESP. Please make sure your YAML file contains an ‘api:’ line.” 

I've updated the yaml file with: 

```
# Your Wi-Fi SSID and password
wifi:
  ssid: "Wifi"
  password: "Password"

api:
  # No password specified here

# Optional: OTA (Over-The-Air) updates
ota:
  # Optional password for OTA updates if needed
```

And still get the same error. 

Certainly I'm not the only one running into this issue?
Edit: Looks like people are running into this issue and there "randomly" resolving. This has to be a bug: 
- https://github.com/EverythingSmartHome/everything-presence-lite/issues/68 
- https://community.home-assistant.io/t/looking-for-help-with-esphome-initial-setup/756820/10
