### ISSUE TITLE
Zone occupancy state issue?

### ISSUE THREAD

**Issue by vague666** [EverythingSmartHome/everything-presence-lite#169]
Not sure what is going on so trying to add all info I can and hope somebody can tell me if it is me doing something wrong or what.
I have the EPL at the end of my hallway and I control the hallway lights with it. The issue is that the lights turn off while I stand in front of it(tying my shoelaces, putting on jacket etc)
Homeassistant automation is waiting for a trigger for EPL to turn occupancy off before continuing the run, and this is where something goes wrong. I can see in state history the state being constantly on but HA still continues the run and the lights turn off. And the automation is not restarted until I leave the EPL zone
![Screenshot 2024-09-16 at 22-31-08 Settings – Home Assistant](https://github.com/user-attachments/assets/20eaa7f9-8842-4cec-8464-b120acb04663)
![Screenshot 2024-09-16 at 22-51-33 Settings – Home Assistant](https://github.com/user-attachments/assets/a16616b4-aba2-4e25-8b3f-689a4676a32f)
[automation.txt](https://github.com/user-attachments/files/17019793/automation.txt)
[history-2.txt](https://github.com/user-attachments/files/17019794/history-2.txt)

**Comment by Draghmar** [comment]
My suggestion would to split this automation. You're saying that EPL Occupancy is on and doesn't change. So the issue most likely lays in the trigger logic. Try to make automation for turning lights on and second for turning off. So basically instead of having await for trigger you'd use automation trigger. For me at least that would tell me if the problem is related to that trigger.

**Comment by vague666** [comment]
For whatever reason, this step fails, ie the automation appears to ignore it completely
(I changed the trigger to device instead of entity but that didn't help either)
```
wait_for_trigger:
  - type: not_occupied
    platform: device
    device_id: 38f2525300333131911163dd7a763dde
    entity_id: bb528ad1afc06a0abb9e7d3cf6c40091
    domain: binary_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 10
timeout:
  hours: 0
  minutes: 0
  seconds: 0
  milliseconds: 0
```

The trace:
```
Executed: September 17, 2024 at 15:58:58
Result:

wait:
  remaining: 0
  trigger: null
```

**Comment by vague666** [comment]
> My suggestion would to split this automation. You're saying that EPL Occupancy is on and doesn't change. So the issue most likely lays in the trigger logic. Try to make automation for turning lights on and second for turning off. So basically instead of having await for trigger you'd use automation trigger. For me at least that would tell me if the problem is related to that trigger.

I shouldn't have to do that. It's clear which step fails and it's the trigger wait. I don't know why though. The trace above is peculiar and I don't know if the firmware is missing something

**Comment by vague666** [comment]
Seems to work now, I hope. For some reason I had to add the from value to the trigger too, ie state change from on to off even though the from state should be optional
In case anyone else is having issues:
```
wait_for_trigger:
  - platform: state
    entity_id:
      - binary_sensor.everything_presence_occupancy
    from: 'on'
    to: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: 10
```
