### ISSUE TITLE
Bought the sensors but nothing works!

### ISSUE THREAD

**Issue by hellcry37** [EverythingSmartHome/everything-presence-lite#221]
I know how to navigate around git or a project:

What seem to be great is the sensor:

What seem to be nonexistent is a proper documentation on what should I replace my non working config with? This is frustrating and takes the joy out of it ...

This is my non working config right after adding wifi and adopting it to esphome:

```yaml
substitutions:
  name: everything-presence-lite-ee941c
  friendly_name: Living Room EPO Lite
packages:
  EverythingSmartTechnology.Everything_Presence_Lite: github://everythingsmarthome/everything-presence-lite/everything-presence-lite-ha.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: xxx


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
```

Noew what should I replace this with?
```
EverythingSmartTechnology.Everything_Presence_Lite: github://everythingsmarthome/everything-presence-lite/everything-presence-lite-ha.yaml@main
```
 since the are a bunch of files with no apparent explanations on what every file represents, what should I use ?

Maybe add in a readme what all files represent as example one that does fries with bluetooth, one that cook eggs without bluetooth etc ... you get my point.

Thanks in advance!
