### ISSUE TITLE
Add Humidity and Temperature support for SCD40 sensor 

### ISSUE THREAD

**Issue by hajar97** [EverythingSmartHome/everything-presence-lite#259]
Currently, SCD40 sensor exposes only CO2 information. It is definitely capable of reading humidity and temperature information as well. I wonder if there is any specific reason why it is not being currently added? For example, you have been testing its addition and came to conclusion that its readings are insufficiently reliable and hence you prefer not to expose them? If so, it would be great for the community to know. 

Until you share that information, here is a simple code to add to ESPHome YAML configuration to expose readings from those sensors including customisable offsets that may be necessary in some scenarios. If there is no objective reason for not exposing readings from these sensors it would be great if you could add their support officially. Thank you.

```
sensor:
  - id: !extend scd40
    temperature:
      name: "Temperature"
      filters:
        - lambda: return x - id(temperature_offset_ui).state;
    humidity:
      name: "Humidity"
      filters:
        - lambda: return x - id(humidity_offset_ui).state;

number:
  - platform: template
    name: "Temperature Offset"
    id: temperature_offset_ui
    unit_of_measurement: "°C"
    min_value: -70
    max_value: 70
    step: 0.1
    mode: box
    update_interval: never
    optimistic: true
    restore_value: true
    initial_value: 15.0
    icon: "mdi:temperature-celsius"
    entity_category: config
  
  - platform: template
    name: "Humidity Offset"
    id: humidity_offset_ui
    unit_of_measurement: "%"
    min_value: -70
    max_value: 70
    step: 0.1
    mode: box
    update_interval: never
    optimistic: true
    restore_value: true
    initial_value: -20.0
    icon: "mdi:cloud-percent"
    entity_category: config
```
