### ISSUE TITLE
Sensor entities of zone 4 are missing

### ISSUE THREAD

**Issue by Nihvel** [EverythingSmartHome/everything-presence-lite#261]
## Problem

All the entities for the device were enabled on HA. `Settings -> Devices and services -> ESPHome -> Everything Presence Lite xxxxxx`
Some entities related to the `Sensors` for `target 4` are missing.

This issue is present on 3 out of 3 (all of them) Everything Presence Lite devices I own.

 **Firmware: 1.2.0 (ESPHome 2024.11.2)** 

### Entities dump

- Dump of all the `Sensors` entities:
```
type: entities
entities:
  - entity: sensor.everything_presence_lite_4f0494_illuminance
    name: Illuminance
  - entity: sensor.everything_presence_lite_4f0494_mmwave_firmware
    name: mmWave Firmware
  - entity: binary_sensor.everything_presence_lite_4f0494_occupancy
    name: Occupancy
  - entity: sensor.everything_presence_lite_4f0494_occupancy_mask_1_target_count
    name: Occupancy Mask 1 Target Count
  - entity: binary_sensor.everything_presence_lite_4f0494_target_1_active
    name: Target 1 Active
  - entity: sensor.everything_presence_lite_4f0494_target_1_angle
    name: Target 1 Angle
  - entity: sensor.everything_presence_lite_4f0494_target_1_distance
    name: Target 1 Distance
  - entity: sensor.everything_presence_lite_4f0494_target_1_resolution
    name: Target 1 Resolution
  - entity: sensor.everything_presence_lite_4f0494_target_1_speed
    name: Target 1 Speed
  - entity: sensor.everything_presence_lite_4f0494_target_1_x
    name: Target 1 X
  - entity: sensor.everything_presence_lite_4f0494_target_1_y
    name: Target 1 Y
  - entity: binary_sensor.everything_presence_lite_4f0494_target_2_active
    name: Target 2 Active
  - entity: sensor.everything_presence_lite_4f0494_target_2_angle
    name: Target 2 Angle
  - entity: sensor.everything_presence_lite_4f0494_target_2_distance
    name: Target 2 Distance
  - entity: sensor.everything_presence_lite_4f0494_target_2_resolution
    name: Target 2 Resolution
  - entity: sensor.everything_presence_lite_4f0494_target_2_speed
    name: Target 2 Speed
  - entity: sensor.everything_presence_lite_4f0494_target_2_x
    name: Target 2 X
  - entity: sensor.everything_presence_lite_4f0494_target_2_y
    name: Target 2 Y
  - entity: binary_sensor.everything_presence_lite_4f0494_target_3_active
    name: Target 3 Active
  - entity: sensor.everything_presence_lite_4f0494_target_3_angle
    name: Target 3 Angle
  - entity: sensor.everything_presence_lite_4f0494_target_3_distance
    name: Target 3 Distance
  - entity: sensor.everything_presence_lite_4f0494_target_3_resolution
    name: Target 3 Resolution
  - entity: sensor.everything_presence_lite_4f0494_target_3_speed
    name: Target 3 Speed
  - entity: sensor.everything_presence_lite_4f0494_target_3_x
    name: Target 3 X
  - entity: sensor.everything_presence_lite_4f0494_target_3_y
    name: Target 3 Y
  - entity: binary_sensor.everything_presence_lite_4f0494_zone_1_occupancy
    name: Zone 1 Occupancy
  - entity: sensor.everything_presence_lite_4f0494_zone_1_target_count
    name: Zone 1 Target Count
  - entity: binary_sensor.everything_presence_lite_4f0494_zone_2_occupancy
    name: Zone 2 Occupancy
  - entity: sensor.everything_presence_lite_4f0494_zone_2_target_count
    name: Zone 2 Target Count
  - entity: binary_sensor.everything_presence_lite_4f0494_zone_3_occupancy
    name: Zone 3 Occupancy
  - entity: sensor.everything_presence_lite_4f0494_zone_3_target_count
    name: Zone 3 Target Count
  - entity: binary_sensor.everything_presence_lite_4f0494_zone_4_occupancy
    name: Zone 4 Occupancy
  - entity: sensor.everything_presence_lite_4f0494_zone_4_target_count
    name: Zone 4 Target Count
title: EPresence 4f0494 Bedroom
```

- Missing entities for `Zone 4` (redacted)
```
    name: Target 4 Active
    name: Target 4 Angle
    name: Target 4 Distance
    name: Target 4 Resolution
    name: Target 4 Speed
    name: Target 4 X
    name: Target 4 Y
```

## Expected behaviour

All entities are enabled, therefore entities related to `Zone 4`.

## Notes

The device is currently configured to detect 4 zones inside the room. The zones were created using the Add-on `Everything Presence Zone Configurator`. The entities were enabled before creating the zones. The zones were created and saved multiple times, but the `sensors` of the `zone 4` never showed up
