### ISSUE TITLE
Everything Presence Lite not detecting motion anymore since update to latest as of 6/10/2025

### ISSUE THREAD

**Issue by x0SiN0x** [EverythingSmartHome/everything-presence-lite#343]
its been a while since I updated my sensors and there have been various updates to ESP home so figured i would get all my devices up to date.  Well the presence one works great however the lite does not.  The console log is full of entries like this

`[08:18:36][W][LD2450:867]: Expected 30 bytes but received 105!`

Does this indicate there is some sort of issue going on?  Caught my eye because it calls out the LD2450

FWIW if i use the hlkradartool the sensor is picking up movement just fine. 

just using a basic config (also tried the no ble option)
```
substitutions:
  name: everything-presence-lite-8fa58c
  friendly_name: Everything Presence Lite 8fa58c
packages:
  EverythingSmartTechnology.Everything Presence Lite: github://everythingsmarthome/everything-presence-lite/everything-presence-lite-ha.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
```

Home Assiustant Details
```
Installation method
Home Assistant OS
Core
2025.5.3
Supervisor
2025.05.3
Operating System
15.2
Frontend
20250516.0
```
