### ISSUE TITLE
Added to HA fine but doesn't appear in the ESPHome Add On

### ISSUE THREAD

**Issue by swampylee** [EverythingSmartHome/everything-presence-lite#4]
Maybe I'm doing something wrong or not doing something I should but I'm pretty sure my EP1 appeared in ESPHome addon after adding it to HA but the Lite doesn't.

**Comment by davidrule1969** [comment]
I added them manually using this .yaml:

```
substitutions:
  name: everything-presence-lite-xxx
  friendly_name: Everything Presence Lite
packages:
  Everything_Smart_Technology.Everything_Presence_Lite: github://everythingsmarthome/everything-presence-lite/everything-presence-lite-ha.yaml@main

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: "your-encyption-key="


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
```
