### ISSUE TITLE
Flashing the EPL with BLE functionality

### ISSUE THREAD

**Issue by jeleniain** [EverythingSmartHome/everything-presence-lite#74]
Hi all,
I am currently trying to figure out how to enable the Bluetooth/ ESPresense functionality on my EPL sensors.
In order to add the to my ESPHome container I had to flash them directly through my own ESPHome instance. For that I used the following yaml code:
```
substitutions:
  name: everything-presence-lite
  friendly_name: Everything Presence Lite
packages:
  Everything_Smart_Technology.Everything_Presence_Lite: github://everythingsmarthome/everything-presence-lite/everything-presence-lite-ha.yaml@main

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
```
My question is, what would I need to change to add the BLE functionality?
If I look at the package 'https://github.com/EverythingSmartHome/everything-presence-lite/blob/main/everything-presence-lite-ha.yaml' it seems to already contain the Bluetooth configurations:

```
packages:
  device_base: !include common/everything-presence-lite-base.yaml
  ld2450_base: !include common/ld2450-base.yaml
  bluetooth_base: !include common/bluetooth-base.yaml
```
But than again I do not see ESPresense to be auto discovered in HA, any idea what I am doing wrong/ my above yaml needs to be adjusted?
Any help is very appreciated!
