### ISSUE TITLE
only one entity discovered. The update entity

### ISSUE THREAD

**Issue by sbeukers** [EverythingSmartHome/everything-presence-lite#78]
Hi can you please help me with the following?
I am definitly missing something.
This is the first ESP device I ever own.

The device discoveres correctly updates and then I have 1 device with 1 entity.
I'ts like it is missing firmware or something.
The name is not automatically  everything-presence-one-xxxx like the tutorial

The device is stable online but no entities are discovered.
I've got a api key etc.

Do I need to upload a .yaml somewhere?

![image](https://github.com/EverythingSmartHome/everything-presence-lite/assets/65311410/f9c603b8-b9db-44ad-98c4-362cf9921218)

![image](https://github.com/EverythingSmartHome/everything-presence-lite/assets/65311410/fc7cb369-4a18-45cf-845d-c40dc26fc579)

```

esphome:
  name: everything-presence-lite
  friendly_name: everything-presence-lite

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

ota:
  password: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Everything-Presence-Lite"
    password: "xxxxxxxxxxxxxxx"

captive_portal:
```

Thank you so much in advance!
