### ISSUE TITLE
OTA module now required

### ISSUE THREAD

**Issue by StayPirate** [EverythingSmartHome/everything-presence-lite#89]
With ESPHome 2024.6.1 the following error occurs at build time:

```
INFO ESPHome 2024.6.1
INFO Reading configuration /config/esphome/everything-presence-lite-2851c4.yaml...
Failed config

At least one platform must be specified for 'ota'; add 'platform: esphome' for original OTA functionality
```

The following template fixed the new requirement for me:

```
substitutions:
  name: everything-presence-lite-285334
  friendly_name: mmWave Bagno in Camera
packages:
  EverythingSmartTechnology.Everything_Presence_Lite: github://everythingsmarthome/everything-presence-lite/everything-presence-lite-ha.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: SQuY0z11BP1b1bBXI5qhLsQ0eqr/FPcaz6gfjeRCgzY=
ota:
  - platform: esphome

safe_mode:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
```

`safe_mode:` is not required, but maybe good to have it?
