### ISSUE TITLE
BLE firmware fails to boot from ESPHome version 2024.5.5, NO-BLE firmware works.

### ISSUE THREAD

**Issue by StayPirate** [EverythingSmartHome/everything-presence-lite#90]
In HA, if I flash the build coming from the following template, then the device goes in boot loop and doesn't work anymore.

```
substitutions:
  name: everything-presence-lite-285334
  friendly_name: mmWave Bagno in Camera
packages:
  EverythingSmartTechnology.Everything_Presence_Lite: github://everythingsmarthome/everything-presence-lite/everything-presence-lite-ha.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: ***********************************************
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
```

If I instead try to build/flash the following template, then the device boot fine.

```
esphome:
  name: test
  friendly_name: test

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "Ocdc7S3RWj0P/UcYCCXwExJz2yZw1aS8uj+3kZMnUcQ="

ota:
  - platform: esphome
    password: "fe295e52c1235cf0aa567c53b7ed947a"

wifi:
  ssid: "test"
  password: "testtesttest"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test Fallback Hotspot"
    password: "testpassword"

captive_portal:
```

This is happening to me since I've updated to ESPHome version 2024.5.5. Is that just me? I have not changed anything on my configuration, I just updated the firmware when HA told me that there was a pending update for my device.
